In [2]:
import pandas as pd

In [3]:
# 上市投信買賣超連結
Tw_IvenBank20_url = 'https://www.twse.com.tw/rwd/zh/fund/TWT44U?response=html'
Tw_IvenBank20_df = pd.read_html(Tw_IvenBank20_url)[0]
Tw_IvenBank20_df

    112年08月15日 投信買賣超彙總表
     Unnamed: 0_level_1  證券代號    證券名稱     買進股數    賣出股數    買賣超股數
0                   NaN  2301     光寶科  3560000  955000  2605000
1                   NaN  2421      建準  2044000       0  2044000
2                   NaN  3715    定穎投控  1844000       0  1844000
3                   NaN  2303      聯電  2153000  417000  1736000
4                   NaN  2368     金像電  1534000       0  1534000
..                  ...   ...     ...      ...     ...      ...
204                 NaN  3059     華晶科        0    2000    -2000
205                 NaN  6533     晶心科        0    1000    -1000
206                 NaN  8478    東哥遊艇        0    1000    -1000
207                 NaN  1590  亞德客-KY     1000    1000        0
208                 NaN  8454     富邦媒     1000    1000        0

[209 rows x 6 columns]

In [4]:
Tw_IvenBank20_df = Tw_IvenBank20_df.iloc[:20, [1,2,5]]
Tw_IvenBank20_df

   112年08月15日 投信買賣超彙總表
                  證券代號  證券名稱    買賣超股數
0                 2301   光寶科  2605000
1                 2421    建準  2044000
2                 3715  定穎投控  1844000
3                 2303    聯電  1736000
4                 2368   金像電  1534000
5                 2376    技嘉  1494000
6                 3035    智原  1421000
7                 3231    緯創  1211000
8                 3044    健鼎  1180000
9                 8112    至上  1055000
10                2337    旺宏  1032000
11                2353    宏碁   956000
12                2449  京元電子   837000
13                2313    華通   660000
14                2347    聯強   641000
15                1319    東陽   600000
16                5469   瀚宇博   599000
17                2382    廣達   598000
18                4915    致伸   595000
19                2883   開發金   579000

In [5]:
Tw_IvenBank20_df.columns = ['證券代號','證券名稱','買超股數']
Tw_IvenBank20_df['買超張數'] = Tw_IvenBank20_df['買超股數']//1000
Tw_IvenBank20_df

    證券代號  證券名稱     買超股數  買超張數
0   2301   光寶科  2605000  2605
1   2421    建準  2044000  2044
2   3715  定穎投控  1844000  1844
3   2303    聯電  1736000  1736
4   2368   金像電  1534000  1534
5   2376    技嘉  1494000  1494
6   3035    智原  1421000  1421
7   3231    緯創  1211000  1211
8   3044    健鼎  1180000  1180
9   8112    至上  1055000  1055
10  2337    旺宏  1032000  1032
11  2353    宏碁   956000   956
12  2449  京元電子   837000   837
13  2313    華通   660000   660
14  2347    聯強   641000   641
15  1319    東陽   600000   600
16  5469   瀚宇博   599000   599
17  2382    廣達   598000   598
18  4915    致伸   595000   595
19  2883   開發金   579000   579

In [7]:
#axis = 1 為指定成欄位
Tw_IvenBank20_df = Tw_IvenBank20_df.drop(['買超股數'], axis=1)
Tw_IvenBank20_df

    證券代號  證券名稱  買超張數
0   2301   光寶科  2605
1   2421    建準  2044
2   3715  定穎投控  1844
3   2303    聯電  1736
4   2368   金像電  1534
5   2376    技嘉  1494
6   3035    智原  1421
7   3231    緯創  1211
8   3044    健鼎  1180
9   8112    至上  1055
10  2337    旺宏  1032
11  2353    宏碁   956
12  2449  京元電子   837
13  2313    華通   660
14  2347    聯強   641
15  1319    東陽   600
16  5469   瀚宇博   599
17  2382    廣達   598
18  4915    致伸   595
19  2883   開發金   579

In [8]:
Tw_IvenBank20_df = Tw_IvenBank20_df.set_index(['證券代號'])

In [9]:
Tw_IvenBank20_df

      證券名稱  買超張數
證券代號
2301   光寶科  2605
2421    建準  2044
3715  定穎投控  1844
2303    聯電  1736
2368   金像電  1534
2376    技嘉  1494
3035    智原  1421
3231    緯創  1211
3044    健鼎  1180
8112    至上  1055
2337    旺宏  1032
2353    宏碁   956
2449  京元電子   837
2313    華通   660
2347    聯強   641
1319    東陽   600
5469   瀚宇博   599
2382    廣達   598
4915    致伸   595
2883   開發金   579